### ISSUE TITLE
Issue on get-volume in Create-Win10-Media.ps1

### ISSUE THREAD

**Issue by biloumaxou** [vmware-samples/euc-samples#109]
when running the following line in Create-Win10-Media.ps1 script: 
> $ISO = (get-volume | Where-Object DriveType -like "CD-ROM")
We may have an unexpected result as the following:
![image](https://user-images.githubusercontent.com/49860924/76331494-84075400-62ef-11ea-8ce8-076851b8932d.png)

In that case, the script cannot run correctly:
![image](https://user-images.githubusercontent.com/49860924/76331721-c597ff00-62ef-11ea-9af9-859c32ddd2be.png)
![image](https://user-images.githubusercontent.com/49860924/76331881-f841f780-62ef-11ea-8f21-bae6dcef397e.png)

I suggest to add other controls like:
> (get-volume | Where-Object {$_.DriveType -like "CD-ROM" -and $_.OperationalStatus -eq "OK" -and $_.Size -gt 
0})

**Comment by brookspeppin** [comment]
Thanks for the feedback! I've updated the script accordingly. One minor tweak to your command though: It should be (get-volume | Where-Object {**$_.**DriveType -like "CD-ROM" -and **$_.**OperationalStatus -eq "OK" -and **$_.**Size -gt 0}). (You forgot the underlines).

Issue resolved.
