### ISSUE TITLE
It's should be 2004 here?

### ISSUE THREAD

**Issue by rk4an** [vmware-samples/euc-samples#146]
https://github.com/vmware-samples/euc-samples/blob/5721ac60fb1aab20d301d2d0c13edd425b16cd9f/Windows-Samples/Custom%20Settings/Windows%20Update%20for%20Business/TargetVersion-2004.xml#L10

**Comment by rterakedis** [comment]
@brookspeppin - can you comment and/or submit a pull request with an update?

**Comment by brookspeppin** [comment]
@rk4an Yes you are correct. It's fixed. Thank you.
