### ISSUE TITLE
Sensors Sample for Assignment is broken with new Assignment policy

### ISSUE THREAD

**Issue by anuraagm0** [vmware-samples/euc-samples#158]
The sensors assignment powershell script no longer assigns the sensors to the devices. The new UI has a field which is for the name of the Assignment Group which is not showing in the PS script. Is there a new API to do the assignment work?

**Comment by josuenegron** [comment]
Please download the script again and refer to the updated readme. I added the fix and some more functionality. Thank you! Happy Holidays!

**Comment by josuenegron** [comment]
Fixed version: https://github.com/vmware-samples/euc-samples/blob/master/Windows-Samples/Sensors/import_sensor_samples.ps1
