### ISSUE TITLE
macOS_Update_Helper

### ISSUE THREAD

**Issue by JeackSong** [vmware-samples/euc-samples#160]
How to upgrade Mac OS Catalina big update Mac OS Big Sur？

**Comment by rterakedis** [comment]
@JeackSong - This process was outlined on [TechZone](https://techzone.vmware.com/managing-major-macos-updates-workspace-one-operational-tutorial).   Admittedly, it is due for an update related to Monterey and Apple Silicon.   I will be updating it in Q1 2022.
