### ISSUE TITLE
Sensors - Assignment type for SCHEDULE must also send NULL value for event_trigger

### ISSUE THREAD

**Issue by anuraagm0** [vmware-samples/euc-samples#164]
In the script if the trigger_type is set to SCHEDULE the event_trigger is not set with any additional parameter, however the JSON expects a NULL value which is not sent in the script. The EVENT triggers have no issues. Just the SCHEDULE

{
  "name": "Assignment Group 1",
  "smart_group_uuids": [
    "ccb7449f-ba65-4e55-9f6d-e312ac34ee11"
  ],
  "trigger_type": "SCHEDULE",
  "event_triggers": []
}

**Comment by josuenegron** [comment]
Thanks for the feedback, do you mind sending me an email jnegron@vmware.com with a few more details.

**Comment by anuraagm0** [comment]
Hello Josue,
When I run the script I am sending this –

.\import_sensor_samples.ps1 `
        -WorkspaceONEServer "https://asXXXX.awmdm.com" `
        -WorkspaceONEAdmin "apiadmin " `
        -WorkspaceONEAdminPW "apipassword " `
        -WorkspaceONEAPIKey "<tenant_code>" `
        -OrganizationGroupName "Group Name" `
        -SmartGroupName "Smart Group Name" `
        -UpdateSensors `
        -TriggerType "SCHEDULE" `

On the console I see the sensors created and assigned but they fail to show the assignment details with the crashed rocket. One thing I noticed that when I use the UI the trigger type in the value which should show “Periodically” it shows blank. I check the API and seems the script is not sending any value for event_trigger as in the API help docs. It just send event_trigger = []. I tried it manually and seems to work without the script in the /API/help page for my 2101 console.

Please let me know if you have other questions.
Thanks,
Anuraag

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by josuenegron** [comment]
Had a quick call with @anuraagm0, we identified the issue. No code changes required.
