### ISSUE TITLE
DelL Provisioning - dontdisplaylastusername - wrong Value

### ISSUE THREAD

**Issue by biloumaxou** [vmware-samples/euc-samples#168]
Hi,
About Command Line to add to set "Interactive logon: Don't display last signed-in" Policy (link to the page here:
https://github.com/vmware-samples/euc-samples/blob/master/Windows-Samples/Tools%20%26%20Utilities/Dell%20Provisioning/DontDisplayLastUsername.md)

the Command Line used is the following:
cmd /c reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v dontdisplaylastusername /t **REG_SZ** /d 1 /f

However, the registry Value seems to be **REG_DWORD** instead of **REG_SZ**:
![image](https://user-images.githubusercontent.com/49860924/120657435-c7198e00-c484-11eb-92db-c7e7b3efe321.png)

Best regards,

**Comment by rterakedis** [comment]
@brookspeppin -- Can you confirm and submit a pull request to change this?

**Comment by brookspeppin** [comment]
Issue fixed. Thanks @biloumaxou
