### ISSUE TITLE
Windows updated to 21h1 when the feature version was set to 20h2

### ISSUE THREAD

**Issue by Hayes71** [vmware-samples/euc-samples#177]
I have setup the rings in WS1, my win10 is in the Pilot ring, I also set the Version to stay on 20h2. However the computer updated over the weekend to 21h1. Is there a conflict with the pilot ring and setting the version?

**Comment by brookspeppin** [comment]
Hi there! There are a couple of reasons why this could happen. Can you double-check the "TargetReleaseVersion" setting under **HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\current\device\Update** to ensure it applied correctly? Also make sure there are no other conflicting policies under the GPO as those will take precedence: **HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsUpdate**

**Comment by Hayes71** [comment]
Yes I confirmed that it did update the registry for the targeted release version of 20H2. I will check the HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsUpdate to verify that there are not any other conflicts..

**Comment by rterakedis** [comment]
Closing - cold thread.
