### ISSUE TITLE
macOS 12.3 and the Migration Tool python script...

### ISSUE THREAD

**Issue by spikehed** [vmware-samples/euc-samples#201]
macOS 12.3 is about to be dropped soon, I was wondering if the Migration Tool will be updated to python3 for compatibility, as /usr/bin/python  will be yanked on macOS 12.3 - reinstalling it via (python.org) pkg will not alleviate compatibility issue as other libs wont work that the migration tool uses like from Foundation import NSBundle, NSLog

**Comment by mzaske3** [comment]
There is an updated migration tool that leverages bash instead of python that you can use across macOS versions.
