### ISSUE TITLE
macOS Updater Utility (mUU) - Prompt for admin credentials

### ISSUE THREAD

**Issue by ThePirat91** [vmware-samples/euc-samples#241]
Hello, the latest version of the script, once performed by a M1 macOS, show to the logged-in user the popup below with the request for admin credentials, making it impossible to initiate an update by a not-admin user on his own M1.
We tried the same version of scripts on a Intel macOS without finding this "anomaly"; the update was carried out automatically without the request for any credential to the user

<img width="329" alt="Screenshot 2022-09-13 at 09 11 10" src="https://user-images.githubusercontent.com/17300013/189847383-fd77f90f-34af-49bd-b22d-05f700c1e6b3.png">

Is it an expected behavior?
The M1 should not behave as the Intel-based, so don't request any credential?

Thanks

**Comment by gregneagle** [comment]
Apple silicon Macs require the credentials of a user who is a "Volume Owner" in order to install software updates (and upgrades to macOS). If this was better integrated with Workspace One, the MDM could use an escrowed Bootstrap Token to avoid the need for user credentials.

**Comment by ThePirat91** [comment]
So we can assume that this is an "expected behavior" (due to the bad integration with WS1) and that, at this moment, there is not any way to bypass the credential prompts?
If so, it would be impossible to do an automatic, unmanned, os update...right?

Thanks

**Comment by Staff-ict-L2** [comment]
Hello, any update on this topic?
Is it confirmed the needing to have a user with admin rights to be able to install updates via the mUU on Silicon?
If it is so, the utility is quite useless imho....
Thanks

**Comment by mzaske3** [comment]
No admin rights are needed by end user to install updates using mUU. I would ensure that you are not pushing a "Software Update" profile from UEM in conjunction with mUU as the Software Update profile will use softwareupdated binary causing the credential prompt.
