### ISSUE TITLE
macOS Updater Utility - "Major update installer download started, exiting....." loop

### ISSUE THREAD

**Issue by 4rm** [vmware-samples/euc-samples#252]
I'm having an issue with a 12.6.1 not being able to upgrade to 13.0. Everything worked fine for a minor update from 12.3 to 12.6.1, but it seems to get stuck in a loop trying to download 13.0

I'm using a Mac mini (M1, 2020), and the same profile _did work_ for an Intel Macbook Pro. It's been looping like this for days, and the internet is definitely fast enough to have fully downloaded the update by now. Please let me know what logs/configurations would be relevant to share, and I can upload them.

![image](https://user-images.githubusercontent.com/3399474/200874275-e2ad61de-d9f7-4c91-adfc-fa6684bb1e75.png)

Thanks!

**Comment by ThePirat91** [comment]
+1
Same issue here on MacBook Pro and iMac with M1/M2 chipset.
No problems at all on Intel-based macOS.

**Comment by mzaske3** [comment]
This should be resolved in revision 10 that is available now.
