### ISSUE TITLE
MUU - API

### ISSUE THREAD

**Issue by yl10401ee** [vmware-samples/euc-samples#267]
### Describe the bug

Hello, I'm having some trouble getting the MUU script working. Some context: followed every step in applying this script in Workspace One.   Everything works fine up until an install has been triggered for an update and the API response is something I don't understand. See below the macOSupdater.log 

- File or directory not found.</h2>
resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>**

<img width="1430" alt="Screenshot 2023-03-03 at 5 51 11 PM" src="https://user-images.githubusercontent.com/126926583/222869434-78f60ce7-edd3-427e-bf18-222afb44549f.png">

Any help would be much appreciated! 

### Reproduction steps

1.Ensured correct steps in applying ClientID, ClientSec, Rest API URL and Token URL
2.Installer in correct path: /Applications/Install macOS Ventura.app
3.
...

### Expected behavior

End user able to see the prompt to defer update or to being. After deferring twice, chose to begin the upgrade. Was expecting the install to happen immediately and follow with a reboot but nothing happened. 

### Additional context

The installer is downloaded via workspace one internal application, because when the script tried to download the installer (after checking that it didn't exist) I came up with the same error as detailed in the image attached.  So once I pushed out the download for the installer, the script recognized the download.  My only problem is when the upgrade gets triggered to begin, nothing happens.

**Comment by mzaske3** [comment]
Also check the API URL you are providing in the variables section. It should have nothing after .com, here is an example of what it should look like:

![image](https://user-images.githubusercontent.com/63124926/223461940-7e06edde-e460-499a-8335-956d7d903b78.png)

**Comment by mzaske3** [comment]
Yes make sure the URL does not have the '/api' in it as that will lead to the 404 errors you were receiving. Are you on MacAdmins slack?

**Comment by yl10401ee** [comment]
No I'm currently not in MacAdmins slack. Looks like I'll have to get an invitation to it.

**Comment by mzaske3** [comment]
Feel free to DM me on there or send me an email at mzaske@vmware.com and I can try to help troubleshoot.

**Comment by gmarnin** [comment]
@yl10401ee [Sign up here](https://www.macadmins.org) for the MacAdmins Slack
