### ISSUE TITLE
macOS Updater Utility (mUU) v11.3 - Download Updates on currentOS > desideredOS

### ISSUE THREAD

**Issue by ThePirat91** [vmware-samples/euc-samples#282]
### Describe the bug

Going to update the script from v11.2 to v11.3, we noticed that on a test macOS, despite the fact that the OS was already at a higher release than desired and set in the configuration profile, the script still attempted to download the minor update indicated in the configuration profile.

![image](https://github.com/vmware-samples/euc-samples/assets/17300013/04a74f1f-2822-444a-a5e5-a9ad64e5e4af)

### Expected behavior

The script should correctly check the currently installed version and not attempt the release update if it is > than the version indicated in the configuration profile (variable "desiredOS")

**Comment by mzaske3** [comment]
This is fixed in the latest revision (12.2)
